-- liquibase formatted sql

-- changeset demaz:1
create table if not exists socks
(
    id                  bigint generated by default as identity primary key,
    item_color          varchar(100),
    material_percentage int,
    units               bigint
);